main: server.h server.cpp client.h client.cpp mc_util.h mc_util.cpp
	g++ server.h server.cpp mc_util.h mc_util.cpp -lpthread -o server.out
	g++ client.h client.cpp mc_util.h mc_util.cpp -lpthread -o client.out